package db

import (
	"fmt"
	"strings"
	"time"

	"github.com/Sirupsen/logrus"
)

type Release struct {
	Name               string
	Version            string
	Time               time.Time
	AddedGithub        bool
	AddedDockerHub     bool
	TriggeredDockerHub bool
}

// GetReleasesToProcess returns a slice of releases that still need to be processed
// in some way
func (c *Client) GetReleasesToProcess() (rels []Release, err error) {
	err = c.DB.Where(Release{AddedGithub: false}).
		Or(Release{AddedGithub: false}).
		Or(Release{AddedDockerHub: false}).
		Or(Release{TriggeredDockerHub: false}).
		Find(&rels).Error
	return
}

// GetReleases returns a slice of all releases
func (c *Client) GetReleases() (rels []Release, err error) {
	err = c.DB.Find(&rels).Error
	return
}

// AddReleases adds all the releases to the database
func (c *Client) AddReleases(rels []Release) error {
	for _, rel := range rels {
		var _rel Release
		db := c.DB.Where(Release{
			Name:    rel.Name,
			Version: rel.Version,
		}).FirstOrCreate(&_rel)
		if err := db.Error; err != nil {
			return err
		}
	}
	return nil
}

func (r *Release) Fields() logrus.Fields {
	return logrus.Fields{
		"name":    r.Name,
		"version": r.Version,
	}
}

func (r *Release) DockerfilePath() string {
	return r.Name + "/Dockerfile"
}

func (r *Release) DockerfileContents() string {
	return fmt.Sprintf("FROM python\nCMD [ \"pip\", \"install\", \"%v==%v\" ]\n", r.Name, r.Version)
}

func (r *Release) GitTagName() string {
	return fmt.Sprintf("%v@%v", strings.ToLower(r.Name), r.Version)
}

func (r *Release) GitTagMessage() string {
	return fmt.Sprintf(
		"Version %v for %v",
		r.Version,
		r.Name,
	)
}

func (r *Release) GitCommitMessage() string {
	return fmt.Sprintf(
		"Adding version %v for %v\n",
		r.Version,
		r.Name,
	)
}

func (r *Release) DockerHubName() string {
	return strings.ToLower(r.Name)
}

func (r *Release) DockerHubTag() string {
	return r.Version
}

func (r *Release) DockerHubRepoShortDescription() string {
	return fmt.Sprintf("%v PyPi package based on python:3", r.Name)
}

func (r *Release) DockerHubRepoFullDescription() string {
	return fmt.Sprintf(`# %[1]v

[Autogenerated build](https://github.com/saulshanabrook/pypi-dockerhub) of [%[1]v PyPi package](https://pypi.python.org/pypi/%[1]v), based on the `+"`python:3`"+` image.

Using the `+"`latest`"+` branch will pull in the last version built.

I recommend pinning to an explicit version number, because it is possible if an old version is built retroactively that it will be set to `+"`latest`"+`.

Check [the tags page](./tags/) for a list of all build version.`, r.Name)
}
